databases:
  default:
    driver: postgres
    dsn: "host=localhost port=5419 user=test password=test dbname=users sslmode=disable"

tasks:
  grpc-crud-1: # step 1: without options
    activities:
      - format: grpc-crud
        table_per_file: true
        spec:
          package: 'org.user_manager'
          with:
            google.api.field_behavior: true
            google.api.http: true
        out:
          dir: './out/grpc-crud-1'

options:
  print_stat: true
  debug: true
