databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

tasks:
  gen_goose_migrations:
    activities:
      - export: goose
        out:
          dir: ./out/goose

options:
  print_stat: true
  debug: true
