databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

tasks:
  gen_goose_migrations:
    activities:
      - export: goose
        out:
          dir: ./out/goose

  gen_laravel_raw_migrations:
    activities:
      - export: laravel-migrations-raw
        table_per_file: true
        spec:
          use:
            if_not_exists: true
            if_exists: true
        out:
          dir: ./out/laravel-migrations-raw

  gen_graphql:
    activities:
      - export: graphql
        table_per_file: true
        out:
          dir: ./out/graphql

options:
  print_stat: true
  debug: true
