databases:
  default:
    driver: postgres
    dsn: "port=5459 user=db password=db dbname=db sslmode=disable"

tasks:
  gen_md:
    activities:
      - export: md
        spec:
          with_diagram: true
        out:
          dir: ./out

options:
  print_stat: true
