databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

tasks:
  gen_goose_migrations:
    activities:
      - export: goose
        out:
          dir: ./out/goose

  gen_laravel_raw_migrations:
    activities:
      - export: laravel-migrations-raw
        out:
          dir: ./out/laravel-migrations-raw

options:
  print_stat: true
  debug: true
