databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

  dbml:
    driver: dbml
    dsn: "./test.dbml"

tasks:
  dbml:
    activities:
      - export: dbml
        out:
          dir: ./out/dbml

  go-entities:
    activities:
      - export: go-entities
        spec:
          go_module: github.com/artarts36/repo
        out:
          dir: ./out/go-entities

  go-entities-per-table:
    activities:
      - export: go-entities
        table_per_file: true
        spec:
          go_module: github.com/artarts36/repo
        out:
          dir: ./out/go-entities-per-table

  go_entity_repository:
    activities:
      - export: go-entity-repository
        out:
          dir: ./out/go-entity-repository

  gen_json_schema:
    activities:
      - export: json-schema
        spec:
          pretty: true
        out:
          dir: ./out/json-schema

  gen_goose_migrations:
    activities:
      - export: goose
        out:
          dir: ./out/goose/common

  gen_goose_migrations_per:
    activities:
      - export: goose
        table_per_file: true
        out:
          dir: ./out/goose/per

  gen_goose_migrations_mysql:
    activities:
      - export: goose
        spec:
          target: mysql
        out:
          dir: ./out/goose_mysql

  gen_laravel_raw_migrations:
    activities:
      - export: laravel-migrations-raw
        table_per_file: true
        spec:
          use:
            if_not_exists: true
            if_exists: true
        out:
          dir: ./out/laravel-migrations-raw

  gen_graphql:
    activities:
      - export: graphql
        table_per_file: true
        out:
          dir: ./out/graphql

options:
  print_stat: true
  debug: true
