databases:
  default:
    driver: postgres
    dsn: "host=localhost port=5419 user=test password=test dbname=users sslmode=disable"

  dbml:
    driver: dbml
    dsn: "./test.dbml"

tasks:
  grpc:
    activities:
      - format: grpc-crud
        table_per_file: true
        spec:
          package: 'org.users'
          with:
            buf.validate.field: true
            google.api.field_behavior: true
            google.api.http:
              path_prefix: '/v1'
        out:
          dir: './grpc-crud'

  diagram:
    activities:
      - format: diagram
        spec:
          style:
            font:
              family: Courier

            background:
              grid:
                line_color: '#ccc'

            table:
              name:
                background_color: '#3498db'
                text_color: 'white'
        out:
          dir: ./

options:
  print_stat: true
  debug: true
