databases:
  default:
    driver: postgres
    dsn: "host=localhost port=5419 user=test password=test dbname=users sslmode=disable"

  dbml:
    driver: dbml
    dsn: "./test.dbml"

tasks:
  diagram:
    activities:
      - format: diagram
        spec:
          style:
            background:
              color: 'green'
              grid:
                cell_size: 10
                line_color: red

            table:
              name:
                background_color: '#3498db'
                text_color: 'white'
        out:
          dir: ./

options:
  print_stat: true
  debug: true
