databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

tasks:
  gen_md:
    activities:
      - export: go-entity-repository
        spec:
          entities:
            package: domain
          repositories:
            package: infrastructure/repositories
            container:
              struct_name: group
        out:
          dir: ./out

options:
  print_stat: true
  debug: true
