databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

tasks:
  gen_repos:
    activities:
      - export: json-schema
        spec:
          pretty: true
        out:
          dir: ./out

options:
  print_stat: true
  debug: true
