name: db-exporter
description: App for export db schema to formats
inputs:
    config:
        description: 'Path to config file (yaml), default: ./.db-exporter.yaml'
        required: false
    tasks:
        description: task names of config file
        required: false
branding:
    icon: archive
    color: yellow
runs:
    using: composite
    steps:
        - name: Download db-exporter binary
          run: wget -O db-exporter.zip https://github.com/ArtARTs36/db-exporter/releases/download/v0.5.7/db-exporter-linux-amd64.zip && unzip -j db-exporter.zip db-exporter
          shell: bash
        - name: Run db-exporter
          id: run-binary
          run: eval "./db-exporter ${CMD_RUN_ARGS}"
          shell: bash
          env:
            CMD_RUN_ARGS: "'${{ inputs.config != '' && format('--config={0}', inputs.config) || '' }}' '${{ inputs.tasks != '' && format('--tasks={0}', inputs.tasks) || '' }}'"
