databases:
  default:
    driver: postgres
    dsn: $PG_DSN # DSN к базе данных Postgres

tasks:
  my-grpc-crud:
    activities:
      - format: grpc-crud
        table_per_file: true # Этот параметр указывает, что для каждой таблицы должен генерироваться отдельный файл
        spec:
          package: 'org.user_manager'
          options:
            go_package: github.com/my-org/user-manager/pkg/api
          with:
            google.api.field_behavior: true # Генерируем опцию field_behavior для полей запросов
            google.api.http: # Генерируем опцию google.api.http для заполнения адреса для методов
              path_prefix: /v1
        out:
          dir: './contracts'
