databases:
  default:
    driver: postgres
    dsn: $PG_DSN

tasks:
  pg_go-structs:
    activities:
      - export: go-structs
        out:
          dir: ./out

  pg_diagram:
    activities:
      - export: diagram
        out:
          dir: ./out

  pg_yaml_fixtures_export:
    activities:
      - export: yaml-fixtures
        out:
          dir: ./out

  pg_grpc-crud:
    activities:
      - export: grpc-crud
        spec:
          package: "org.service"
          options:
            optimize_for: SPEED
        out:
          dir: ./out

  pg_csv_export:
    activities:
      - export: csv
        spec:
          delimiter: ','
        out:
          dir: ./out

options:
  print_stat: true
  debug: true
