name: e2e

on:
  push:
    branches: ['master']
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'templates/**'
      - 'functest/**'
      - go.mod
      - go.sum
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: sudo apt install gcc

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: stable

      - name: Install Go dependencies
        run: go mod download

      - name: Build
        env:
          FUNCTEST: on
          MYSQL_DSN: test:test@tcp(localhost:5499)/users
          DB_EXPORTER_BIN: ${{ github.workspace }}/functest/db-exporter
        run: go build -o ./functest/db-exporter cmd/main.go

      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: ./functest/db-exporter

  postgres:
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: users
        ports:
          - 5499:5432

    name: tests with postgres
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: install deps
        run: sudo apt install gcc

      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v5
        with:
          name: binary
          path: ./functest

      - name: Run functional tests
        env:
          FUNCTEST: on
          PG_DSN: host=localhost port=5499 user=test password=test dbname=users sslmode=disable
          DB_EXPORTER_BIN: ${{ github.workspace }}/functest/db-exporter
        run: chmod +x ./functest/db-exporter && go test ./functest

  mysql:
    services:
      postgres:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: users
        ports:
          - 5499:3306

    name: tests with mysql
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v5
        with:
          name: binary
          path: ./functest

      - name: Run functional tests
        env:
          FUNCTEST: on
          MYSQL_DSN: test:test@tcp(localhost:5499)/users
          DB_EXPORTER_BIN: ${{ github.workspace }}/functest/db-exporter
        run: chmod +x ./functest/db-exporter && go test ./functest
