name: update github action config
on:
  push:
    branches:
      - master

jobs:
  update-ga-config:
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: sudo apt install gcc

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: stable

      - name: Install Go dependencies
        run: go mod download

      - name: Generate new config
        run: |
          go run ./cmd/main.go --singlecli-codegen-ga
          git add action.yaml
          git commit -m "chore: actualize ga config"
          git push
